### ISSUE TITLE
dead links on v1.8.1 specifications, introduction and examples page

### ISSUE THREAD

**Issue by apastor** [NeuroML/NeuroMLWebsite#1]
It seems, at least on my computer, that all links to https://www.neuroml.org/NeuroMLValidator/...
are dead. The contact page https://www.neuroml.org/contacts doesn't work too.

**Comment by pgleeson** [comment]
Thanks @apastor, we're aware of some of the issues with neuroml.org and are looking into them at the moment.

**Comment by scrook** [comment]
Should be fixed now.

**Comment by scrook** [comment]
apastor, where did you see the contacts page link? I don't think we have a contacts page anymore.

**Comment by pgleeson** [comment]
http://www.neuroml.org/contacts.php, which used to be a valid page on the old website, now successfully redirects to http://www.neuroml.org/scientific_committee
