### ISSUE TITLE
Add NetPyNE to the NeuroML website software page

### ISSUE THREAD

**Issue by joewgraham** [NeuroML/NeuroMLWebsite#17]
It would be great to have NetPyNE listed as a NeuroML-compatible software tool on the website tool support page: https://neuroml.org/tool_support

Here's a link to the NetPyNE documentation:
http://netpyne.org/

To the logo:
http://netpyne.org/_static/logo.png

Here's an appropriate blurb:

NetPyNE is a <a href="https://github.com/Neurosim-lab/netpyne">Python package</a> to facilitate the development, simulation, parallelization, analysis, and optimization of biological neuronal networks using the NEURON simulator.  NetPyNE can import from and export to NeuroML.

The NetPyNE <a href="https://github.com/MetaCell/NetPyNE-UI/wiki"> Graphical User Interface</a> allows people with no coding experience to develop, run, analyze, and export simulations of neuronal networks from their web browser.

**Comment by pgleeson** [comment]
Yes, I've been planning an overhaul of the tools page for a while. Will certainly include NetPyNE there.

**Comment by scrook** [comment]
We have a student here who I asked to make this addition. He can make such small changes until Padraig has time for an overhaul.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ChihweiLHBird** [comment]
Thanks, and I will finish this soon.

**Comment by pgleeson** [comment]
I knew I had opened an issue related to this before... A full list of the tools that need to be added along with suggestions to reorganise the page are at: https://github.com/NeuroML/NeuroML2/issues/127

**Comment by ChihweiLHBird** [comment]
> It would be great to have NetPyNE listed as a NeuroML-compatible software tool on the website tool support page: https://neuroml.org/tool_support
> 
> Here's a link to the NetPyNE documentation:
> http://netpyne.org/
> 
> To the logo:
> http://netpyne.org/_static/logo.png
> 
> Here's an appropriate blurb:
> 
> NetPyNE is a [Python package](https://github.com/Neurosim-lab/netpyne) to facilitate the development, simulation, parallelization, analysis, and optimization of biological neuronal networks using the NEURON simulator. NetPyNE can import from and export to NeuroML.
> 
> The NetPyNE [ Graphical User Interface](https://github.com/MetaCell/NetPyNE-UI/wiki) allows people with no coding experience to develop, run, analyze, and export simulations of neuronal networks from their web browser.

Hi, 

Cloud you please tell me that
does it support morphologically detailed single cells;
does it support networks of morphologically detailed cells;
does it support models containing active membrane conductances through ion channels;
does it support (large scale) networks of single compartment neurons;
does it includes support for NeuroML v2.0?

**Comment by scrook** [comment]
Yes to all.

Sharon Crook
Professor
School of Mathematical and Statistical Sciences
Barrett Honors Faculty
Arizona State University

Mailcode: 1804
Tempe, Arizona 85287-1804
email: sharon.crook@asu.edu
phone: 480-965-0403
web: https://iconlab.asu.edu
twitter: @SharCrook


________________________________________

**Comment by ChihweiLHBird** [comment]
Pull request created.
https://github.com/NeuroML/NeuroMLWebsite/pull/18

**Comment by pgleeson** [comment]
Updated on live site.

**Comment by joewgraham** [comment]
Looks great, thanks!
