### ISSUE TITLE
NeuroML validator on "tool support" page does not work

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/NeuroMLWebsite#19]
https://neuroml.org/tool_support has a link to a validator: http://neuroml.org/NeuroMLValidator/Validation.jsp

I can't seem to get it to work, here on Firefox 83. Something does come up, but it's blank:

![neuroml-validator-firefox](https://user-images.githubusercontent.com/102575/100358917-c0e6b880-2fee-11eb-9561-9bf71ff09cca.png)

**Comment by pgleeson** [comment]
That was only a validator for v1.x, and has not been working for a while. Best to plan to remove, as we don't really support that version anymore...
BTW jnml will also validate v1 files with: 
    
    jnml -validatev1 xx.xml
