### ISSUE TITLE
Difficult to reach documentation

### ISSUE THREAD

**Issue by tarelli** [NeuroML/NeuroMLWebsite#2]
It is difficult to find the NeuroML documentation https://neuroml.org/NeuroML2CoreTypes/Cells.html (I'm not even sure if it's linked anywhere)

**Comment by pgleeson** [comment]
I've fixed a broken link on the main [getNeuroML](https://neuroml.org/getneuroml) page & made it clearer where the source LEMS can be found.

They're also linked from here: https://neuroml.org/lems_dev

**Comment by pgleeson** [comment]
Ok to close this @tarelli?

**Comment by tarelli** [comment]
+1
