### ISSUE TITLE
https for NeuroML website still using the wrong certificate

### ISSUE THREAD

**Issue by pgleeson** [NeuroML/NeuroMLWebsite#4]
![screen shot 2015-06-10 at 10 26 20](https://cloud.githubusercontent.com/assets/1556687/8079250/2e2ad742-0f5b-11e5-954e-4c4a8ed8a3e0.png)

@JustasB, @scrook could you look into this, maybe ask Renate the curent status?

**Comment by JustasB** [comment]
Interestingly, I'm getting this problem only on Firefox in Win 7. No warning on Mac FF, Safari, or Chrome, or on Win Chrome, and IE8.

According to this:
http://www.networking4all.com/en/support/tools/site+check/report/?fqdn=neuroml.org&protocol=https

> this indicates that not all intermediate certificates are installed on the server

And this: 
https://spaces.internet2.edu/display/InCCollaborate/InCommon+Cert+Service+FAQ#InCommonCertServiceFAQ-WhyisthebrowserrejectingmySSL/TLScertificate?

> the intermediate CA certificate in the certificate chain has not been configured correctly on the server. (A certificate issued by the InCommon Certificate Service has a chain length of three, with one intermediate CA certificate.) Consult your server documentation how to install the intermediate CA certificate on the server.

I'll work with Renate on the intermediate cert.

**Comment by scrook** [comment]
Thank You!

Sharon Crook
OCNS 2015 Travel Chair
Arizona State University
http://math.la.asu.edu/~crook
http://neuroml.org

**Comment by JustasB** [comment]
@pgleeson @scrook This should be fixed. Please try again.

**Comment by pgleeson** [comment]
Not quite yet @JustasB... The certificate is only for neuroml.org, not www.neuroml.org:

![selection_224](https://cloud.githubusercontent.com/assets/1556687/8278366/a487f18e-18c2-11e5-959f-6d288669f482.png)

**Comment by JustasB** [comment]
Emailed Renate to get the wildcard cert.

**Comment by JustasB** [comment]
https://www.neuroml.org should be working now.

**Comment by pgleeson** [comment]
Seems to be working fine now
