### ISSUE TITLE
neuroml.org redirecting to neuroml-db.org

### ISSUE THREAD

**Issue by pgleeson** [NeuroML/NeuroMLWebsite#5]
Not the intended behaviour I presume @scrook @JustasB...?

**Comment by pgleeson** [comment]
Try on your cellphone too; firefox which I normally use works fine, chrome redirects..

**Comment by pgleeson** [comment]
http://dendrite.asu.edu/ also redirecting to neuroml-db.org... 

@JustasB, please have a look at this as soon as you can; all of neuroml.org is inaccessible..

**Comment by JustasB** [comment]
This has been fixed. There were a zillion random apache config files left over from who knows when. I cleaned up dendrite and it should all be working ok.

**Comment by pgleeson** [comment]
Ok, works fine here now. Thanks.
