### ISSUE TITLE
CRNCS 2014 site navigation broken

### ISSUE THREAD

**Issue by JustasB** [NeuroML/NeuroMLWebsite#9]
> Justas,
> 
> I'm not sure what is wrong, but the navigation isn't working on the CRCNS website. Let me know if you can have a look. Otherwise I will try to fix it.
> 
> Sharon Crook

**Comment by JustasB** [comment]
Fixed: https://neuroml.org/CRCNS2014_Web/
Checking in a PR with missing folder

**Comment by pgleeson** [comment]
Ok, merged...
